# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_type.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12message_type.proto\"~\n\x0c\x43OMM_MESSAGE\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.COMM_MESSAGE.TYPE\x12\n\n\x02N1\x18\x04 \x01(\x05\x12\x0f\n\x07N1_hash\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x1e\n\x04TYPE\x12\x0b\n\x07\x43ONFIRM\x10\x00\x12\t\n\x05LOGIN\x10\x01\x62\x06proto3')
)



_COMM_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='TYPE',
  full_name='COMM_MESSAGE.TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONFIRM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=148,
)
_sym_db.RegisterEnumDescriptor(_COMM_MESSAGE_TYPE)


_COMM_MESSAGE = _descriptor.Descriptor(
  name='COMM_MESSAGE',
  full_name='COMM_MESSAGE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='COMM_MESSAGE.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='N1', full_name='COMM_MESSAGE.N1', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='N1_hash', full_name='COMM_MESSAGE.N1_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='COMM_MESSAGE.payload', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMM_MESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=148,
)

_COMM_MESSAGE.fields_by_name['type'].enum_type = _COMM_MESSAGE_TYPE
_COMM_MESSAGE_TYPE.containing_type = _COMM_MESSAGE
DESCRIPTOR.message_types_by_name['COMM_MESSAGE'] = _COMM_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

COMM_MESSAGE = _reflection.GeneratedProtocolMessageType('COMM_MESSAGE', (_message.Message,), {
  'DESCRIPTOR' : _COMM_MESSAGE,
  '__module__' : 'message_type_pb2'
  # @@protoc_insertion_point(class_scope:COMM_MESSAGE)
  })
_sym_db.RegisterMessage(COMM_MESSAGE)


# @@protoc_insertion_point(module_scope)
